### ISSUE TITLE
Problem z połączeniem kamery i wiaderka

### ISSUE THREAD

**Issue by matisiekpl** [JavaDevMatt/tutorialclicker#1]
Hej, 

Link: https://github.com/MatisiekPL/royal-miner

ostatnio oglądam twoje filmy z Libgdx'a i pomyślałem, aby zrobić coś w stylu Pokemon Go z GPS'em w formie 2d. Gra ma polegać na tym, aby budować kopalnie w swoim mieście i wydobywać surowce. Obecnie robię prototyp (podobno to dobra praktyka), lecz po uruchomieniu nawet w Desktopie, mam cały czas czerwony ekran, choć niby zmieniałem kolor tła. Myślę, że SpriteBatch nie połączył się z kamerą i przez to nie mogę manipulować ekranem. I tu moja prośba: przyglądnij się kodowi i sprawdź co może być tego przyczyną. Jakbyś coś więcej zauważył (np. złe praktyki) to pisz śmiało. Mam dopiero 14 lat i jeszcze się uczę...

Dzięki, z życzeniami czystego kodu ;),
Mateusz Woźniak

**Comment by DawidStankiewicz** [comment]
Hej, 
zapraszam do facebookowej grupy założonej specjalnie do zadawania takich pytań jak twoje. [https://www.facebook.com/groups/javadevmatt/](https://www.facebook.com/groups/javadevmatt/)

**Comment by matisiekpl** [comment]
Dzięki...
